_format_version: "3.0"
_transform: true

plugins:
  - name: prometheus
    config:
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true

services:
  - name: auth-service
    url: http://auth-service:8000
    routes:
      - name: auth-api
        paths:
          - /auth
        strip_path: false
        methods:
          - GET
          - POST
          - OPTIONS

  - name: chat-service
    url: http://chat-service:8080
    routes:
      - name: chat-api
        paths:
          - /api
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
          - PATCH
      - name: chat-ws
        paths:
          - /ws
          - /ws-plain
        strip_path: false
        protocols:
          - http
          - https

  - name: reporting-service
    url: http://reporting-service:8083
    routes:
      - name: reporting-api
        paths:
          - /reports
        strip_path: false
        methods:
          - GET
          - OPTIONS

  - name: frontend
    url: http://frontend:80
    routes:
      - name: frontend-root
        paths:
          - /
        strip_path: false
        methods:
          - GET
          - HEAD
          - OPTIONS
