spring:
  application:
    name: reporting-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:read-replica-db}:${DB_PORT:5432}/${DB_NAME:main}
    username: ${DB_USER:user}
    password: ${DB_PASS:pass}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8000/auth/jwks

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: reporting-service
